#!/usr/bin/env bash

grep=""
dry_run="0"

while [[ $# -gt 0 ]]; do
    echo "ARG: \"$1\""
    if [[ "$1" == "--dry" ]]; then
        dry_run="1"
    else
        grep="$1"
    fi
    shift
done

log() {
    if [[ "$dry_run" == "1" ]]; then
        echo "[DRY_RUN]: $1"
    else
        echo "$1"
    fi
}

log "RUN: grep=\"$grep\" dry_run=$dry_run"

runs_dir="./runs"

scripts=$(find "$runs_dir" -mindepth 1 -maxdepth 1 -type f -executable | sort)

for s in $scripts; do
    script_name="$(basename "$s")"

    if [[ -n "$grep" ]] && ! echo "$script_name" | grep -q "$grep"; then
        log "grep \"$grep\" filtered out $script_name"
        continue
    fi

    log "running script: $script_name"

    if [[ "$dry_run" == "0" ]]; then
        "$s"
    fi
done

